services:
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - app
    networks:
      - prisma-network

  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5432}:5432"
    networks:
      - prisma-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:8.6.2-alpine
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - prisma-network
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "${REDISINSIGHT_PORT:-5540}:5540"
    networks:
      - prisma-network
    depends_on:
      - redis

  app:
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
    restart: always
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    networks:
      - prisma-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  prisma-network:


volumes:
  postgres_data:
  redis_data:
