services:
  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - prisma-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:8.6.2-alpine
    restart: always
    networks:
      - prisma-network
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  app:
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
    restart: always
    ports:
      - "127.0.0.1:${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    networks:
      - prisma-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  prisma-network:


volumes:
  postgres_data:
  redis_data:
