name: CI Pipeline

on:
  push:
    branches: [ "main", "dev"]
  pull_request:
    branches: [ "main", "dev"]

jobs:
  build-lint-test:
    name: Run Linter and Tests
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.25.0

      - name: 🟢 Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24.14.1'
          cache: 'pnpm'

      - name: 📥 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🗄️ Generate Prisma Client
        run: pnpm --filter ./app/backend exec prisma generate

      - name: 🔍 Run Linter
        run: pnpm --filter ./app/backend run lint

      - name: 🧪 Run Tests
        run: pnpm --filter ./app/backend run test